version: '2'
services:
  myredis:
    image: redis:3.0
    command: redis-server --requirepass yourpassword
  app:
    build: .
    image: railsapp
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - myredis
    environment:
      - REDIS_URL=redis://:yourpassword@myredis:6379/0/cache
