version: '2'
services:
  redis:
    image: redis
    command: redis-server --requirepass yourpassword
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:yourpassword@redis:6379/0/cache
