# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 177fa5666e10cdea200e76b42093b88dfdf147f673d736b9a170661a8111c99ec4950539fac93c55eaae780ab53372e8b607af21c8908a94c8a9be483874ef76

test:
  secret_key_base: c6f351ad9ba0b32847c6d8a546470143df58dca2d8fb2e6b4c7d13d9a905a743cf3b8cc1ce9cafa3a781b9730d71c0583a31c5e80e0b14b9c008eb72ce4ae03f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
